databaseChangeLog:
  - include:
      file: ./changelog/V1753044960768__create-cms-schema.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753048887645__add-category-table.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050199736__add-language-table.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050576950__add-programme-table.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050576951__add-episode-table.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050576952__create-user-table-and-sequence.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050576953__add-role-table-and-sequence.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050576954__add-user-role-table-and-sequence.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753050576955__add-content-editor-and-content-manager.sql
      relativeToChangelogFile: true
  - include:
      file: ./changelog/V1753360955371__add-missing-columns-published-date-and-thumbnail.sql
      relativeToChangelogFile: true
